# Generated by Django 4.1.7 on 2023-03-29 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_products_brand_alter_products_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='custem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, default='0', null=True)),
                ('zipcode', models.IntegerField(blank=True, default='0', null=True)),
                ('state', models.CharField(blank=True, choices=[('sgASDgh', 'sdbvs'), ('sdbdb', 'sdbsdb'), ('sdvgsdgv', 'sdvbsd'), ('MdsvK', 'sdgv'), ('vcxb', 'gkh'), ('uhjgk', 'Ghrhtee'), ('srh', 'rh-rheth')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
