# Generated by Django 4.1.7 on 2023-04-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordred',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordred_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordred_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
